kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: irohide-egress-deployment
  namespace: default
  labels:
    k8s-app: ironhide-vnf
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ironhide-vnf
  template:
    metadata:
      labels:
        k8s-app: ironhide-vnf
        name: ironhide-vnf
    spec:
      containers:
      - name: ironhide
        image: augugrumi/ironhide:latest
        args: ["-e"]
        imagePullPolicy: Always
        ports:
        - name: udp
          containerPort: 8778
          protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: ironhide-egress-service
  namespace: default
spec:
  selector:
    k8s-app: ironhide-vnf
  ports:
  - name: udp
    port: 8778
    protocol: UDP
  type: NodePort